#!/bin/bash
yum update -y
yum install wget -y
wget https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh
sleep 3
bash hst-install.sh --force --named yes --vsftpd yes --proftpd no --iptables yes --fail2ban yes --quota no --exim no --dovecot no --spamassassin no --clamav no --mysql yes --postgresql no --hostname hostname.domain.tld --email watari@gmx.fr
#sleep 20


rm -rf /home/admin/conf/web/server.sonderbak.com.nginx.conf
read -p "Please enter current server ip " ip1
read -p "please enter destination server ip "  ip

echo "server {
    listen      $ip1:80;
    server_name sonderbak.com www.sonderbak.com;
    error_log  /var/log/httpd/domains/server.sonderbak.com.error.log error;
    location / {
        proxy_pass      http://$ip;
} }" >> /home/admin/conf/web/server.sonderbak.com.nginx.conf

service nginx restart
