#!/bin/bash
apt update -y && apt upgrade -y
apt install wget -y
wget https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh
sleep 3
sudo bash hst-install.sh --port '2083' --lang 'en' --hostname 'server.voiranime.com' --email 'voiranime@gmx.fr' --password 'rpTBz4\3f:U7dZ5dU8Gs' --apache yes --phpfpm no --multiphp no --vsftpd no --proftpd no --named no --mysql no --mysql-classic no --postgresql no --exim no --dovecot no --sieve no --clamav no --spamassassin no --iptables no --fail2ban yes --quota no --api no --interactive yes --force yes   
#sleep 20


rm -rf /home/admin/conf/web/server.voiranime.com.nginx.conf
read -p "Please enter current server ip " ip1
read -p "please enter destination server ip "  ip

echo "server {
    listen      $ip1:80;
    server_name voiranime.com www.voiranime.com x1.voiranime.com;
    error_log  /var/log/httpd/domains/server.voiranime.com.error.log error;
    location / {
        proxy_pass      http://$ip;
} }" >> /home/admin/conf/web/server.voiranime.com.nginx.conf

service nginx restart
