#!/bin/bash
apt update 
apt install nginx -y
 
rm -rf /etc/nginx/sites-enabled/default
read -p "Please enter current server ip " ip1
read -p "please enter destination server ip "  ip
 
echo "server {
    listen      $ip1:80;
    server_name voiranime.com *.voiranime.com;
    error_log  /var/log/httpd/domains/server.voiranime.com.error.log error;
 
    location / {
		proxy_set_header Host $host;
        proxy_pass      http://$ip:80;
} }" > /etc/nginx/sites-enabled/default
 
service nginx restart
