#!/bin/bash
yum update -y
rm -f /etc/sysconfig/selinux
rm -f /etc/selinux/config
wget https://raw.githubusercontent.com/armpdq/configs/master/selinux -O /etc/selinux/config
wget https://raw.githubusercontent.com/armpdq/configs/master/selinux -O /etc/sysconfig/selinux
setenforce 0
curl -O http://vestacp.com/pub/vst-install.sh
sleep 3
bash vst-install.sh --nginx yes --apache yes --phpfpm no --named no --remi no --vsftpd no --proftpd no --iptables no --fail2ban no --quota no --exim no --dovecot no --spamassassin no --clamav no --softaculous no --mysql no --postgresql no --hostname server.japnovel.com --email info@japnovel.com --force
#sleep 20


rm -rf /home/admin/conf/web/server.japnovel.com.nginx.conf
read -p "Please enter current server ip " ip1
read -p "please enter destination server ip "  ip

echo "server {
    listen      $ip1:80;
    server_name japnovel.com www.japnovel.com;
    error_log  /var/log/httpd/domains/server.japnovel.com.error.log error;
    location / {
        proxy_pass      http://$ip;
} }" >> /home/admin/conf/web/server.japnovel.com.nginx.conf

service nginx restart
